import type { DemandRelease } from "./demand-types";
import { LEARNING_POLICY, tuitionCents } from "./learning-policy";

export interface ResearchEntry {
	readonly id: string;
	readonly name: string;
	readonly prerequisiteIds: readonly string[];
	readonly tier: number;
	readonly durationHours: number;
	readonly monthlyTuitionCents: number;
	readonly release: DemandRelease;
}

function tech(
	id: string,
	name: string,
	prerequisiteIds: readonly string[],
	tier: number,
	durationHours: number,
	monthlyTuition: number,
	release: DemandRelease,
): ResearchEntry {
	return {
		id,
		name,
		prerequisiteIds,
		tier,
		durationHours,
		monthlyTuitionCents: tuitionCents(monthlyTuition),
		release,
	};
}

export const RESEARCH_CATALOG: Record<string, ResearchEntry> = {
	"application-runtime": tech("application-runtime", "Application Runtime", [], 0, 0, 0, "v1"),
	"relational-database": tech("relational-database", "Relational Database", [], 0, 0, 0, "v1"),
	"background-workers": tech(
		"background-workers",
		"Background Workers",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"job-scheduler": tech("job-scheduler", "Job Scheduler", ["background-workers"], 2, 336, 80, "v1"),
	"message-queue": tech("message-queue", "Message Queue", ["background-workers"], 2, 336, 80, "v1"),
	"in-memory-cache": tech(
		"in-memory-cache",
		"In-memory Cache",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"object-storage": tech(
		"object-storage",
		"Object Storage",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"search-engine": tech(
		"search-engine",
		"Search Engine",
		["relational-database"],
		1,
		168,
		40,
		"expansion",
	),
	"event-streaming": tech(
		"event-streaming",
		"Event Streaming",
		["message-queue"],
		3,
		504,
		160,
		"expansion",
	),
	"analytics-database": tech(
		"analytics-database",
		"Analytics Database",
		["relational-database"],
		1,
		168,
		40,
		"expansion",
	),
	"email-delivery": tech(
		"email-delivery",
		"Email Delivery",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"mailbox-hosting": tech(
		"mailbox-hosting",
		"Mailbox Hosting",
		["email-delivery"],
		2,
		336,
		80,
		"v1",
	),
	"real-time-messaging": tech(
		"real-time-messaging",
		"Real-time Messaging",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"payment-gateway-integration": tech(
		"payment-gateway-integration",
		"Payment Gateway Integration",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"media-transcoding": tech(
		"media-transcoding",
		"Media Transcoding",
		["background-workers", "object-storage"],
		2,
		336,
		80,
		"v1",
	),
	"video-on-demand": tech(
		"video-on-demand",
		"Video on Demand",
		["media-transcoding"],
		3,
		504,
		160,
		"v1",
	),
	"live-streaming": tech(
		"live-streaming",
		"Live Streaming",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"real-time-audio-and-video": tech(
		"real-time-audio-and-video",
		"Real-time Audio and Video",
		["real-time-messaging"],
		2,
		336,
		80,
		"expansion",
	),
	"multiplayer-game-server": tech(
		"multiplayer-game-server",
		"Multiplayer Game Server",
		["real-time-messaging"],
		2,
		336,
		80,
		"expansion",
	),
	"authoritative-dns": tech(
		"authoritative-dns",
		"Authoritative DNS",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"reverse-proxy": tech(
		"reverse-proxy",
		"Reverse Proxy",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"load-balancing": tech("load-balancing", "Load Balancing", ["reverse-proxy"], 2, 336, 80, "v1"),
	"health-checks": tech(
		"health-checks",
		"Health Checks",
		["monitoring", "load-balancing"],
		3,
		504,
		160,
		"v1",
	),
	"content-delivery-network": tech(
		"content-delivery-network",
		"Content Delivery Network",
		["object-storage", "reverse-proxy"],
		2,
		336,
		80,
		"expansion",
	),
	"rate-limiting": tech(
		"rate-limiting",
		"Rate Limiting",
		["reverse-proxy"],
		2,
		336,
		80,
		"expansion",
	),
	"private-networking": tech(
		"private-networking",
		"Private Networking",
		["application-runtime"],
		1,
		168,
		40,
		"expansion",
	),
	monitoring: tech("monitoring", "Monitoring", ["application-runtime"], 1, 168, 40, "v1"),
	"backup-and-restore": tech(
		"backup-and-restore",
		"Backup and Restore",
		["relational-database"],
		1,
		168,
		40,
		"v1",
	),
	"database-replication": tech(
		"database-replication",
		"Database Replication",
		["relational-database"],
		1,
		168,
		40,
		"v1",
	),
	"automatic-failover": tech(
		"automatic-failover",
		"Automatic Failover",
		["database-replication", "monitoring"],
		2,
		336,
		80,
		"v1",
	),
	"automated-restart": tech(
		"automated-restart",
		"Automated Restart",
		["monitoring"],
		2,
		336,
		80,
		"v1",
	),
	"container-runtime": tech(
		"container-runtime",
		"Container Runtime",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"container-orchestration": tech(
		"container-orchestration",
		"Container Orchestration",
		["container-runtime", "monitoring"],
		2,
		336,
		80,
		"v1",
	),
	autoscaling: tech(
		"autoscaling",
		"Autoscaling",
		["container-orchestration", "load-balancing"],
		3,
		504,
		160,
		"v1",
	),
	"batch-computing": tech(
		"batch-computing",
		"Batch Computing",
		["job-scheduler"],
		3,
		504,
		160,
		"v1",
	),
	"gpu-computing": tech("gpu-computing", "GPU Computing", ["background-workers"], 2, 336, 80, "v1"),
	"model-serving": tech(
		"model-serving",
		"Model Serving",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
	"model-training": tech(
		"model-training",
		"Model Training",
		["batch-computing"],
		4,
		840,
		320,
		"expansion",
	),
	"vector-search": tech(
		"vector-search",
		"Vector Search",
		["search-engine"],
		2,
		336,
		80,
		"expansion",
	),
	"distributed-computing": tech(
		"distributed-computing",
		"Distributed Computing",
		["batch-computing", "private-networking"],
		4,
		840,
		320,
		"expansion",
	),
	"distributed-gpu-training": tech(
		"distributed-gpu-training",
		"Distributed GPU Training",
		["model-training", "gpu-computing", "distributed-computing"],
		4,
		840,
		320,
		"expansion",
	),
	checkpointing: tech("checkpointing", "Checkpointing", ["batch-computing"], 4, 840, 320, "v1"),
	"quality-checks": tech(
		"quality-checks",
		"Quality Checks",
		["application-runtime"],
		1,
		168,
		40,
		"v1",
	),
};

export function researchById(id: string): ResearchEntry {
	const entry = RESEARCH_CATALOG[id];

	if (entry === undefined) {
		throw new Error(`unknown research: ${id}`);
	}

	return entry;
}

export const BASE_RESEARCH_IDS: readonly string[] = LEARNING_POLICY.baseTechnologyIds;
